### ISSUE TITLE
Looks like your website is down...

### ISSUE THREAD

**Issue by bokub** [sramezani/resume-builder#13]
Just wanted to be sure you knew: 

![image](https://user-images.githubusercontent.com/17952318/114403511-26ee6980-9ba5-11eb-9ddf-e8038abce551.png)

**Comment by sramezani** [comment]
Thanks for the update. Yes, I have a server issue. I need to change the server.

P.S. Server cost is too much for me. I need to find a cheaper server.

**Comment by bokub** [comment]
Thanks for the quick reply !
Could we expect a fix soon ? Or do you plan to do that in a few days/weeks ?

Thanks!

**Comment by sramezani** [comment]
As I mentioned above. The server cost is too much for me. I need to find a cheaper server.
I think I will fix it in the next few days.

**Comment by bokub** [comment]
Thanks !

**Comment by bokub** [comment]
If I can make a suggestion, you could try going serverless and deploy for free on Vercel, and use the free tier of Mongo Atlas

I don't know if you have much traffic, but you could end up paying nothing at all except for the domain

**Comment by sramezani** [comment]
Currently, I using the free tier of Mongo :)
Vercel is a good suggestion, I will looking and probably try it.

**Comment by bokub** [comment]
By the way, in the `/download` route,  can I ask why you save data in the database, then display the `/preview` page which will query the same data? Isn't it the kind of thing that costs a lot of DB storage?

https://github.com/sramezani/resume-builder-server/blob/master/routes/download.js#L32-L41

If you want my opinion, it would be a lot easier to pass the JSON encoded in the URL fragment (to bypass URL length limit), and retrieve it client-side, something like this:


```js
// download.js
const url = `https://https://wtfresume.com/preview?export=true#${encodeURIComponent(JSON.stringify(req.body))}`

// preview/index.tsx
    componentDidMount() {
        const exportStatus = Util.getQueryString(window.location, 'export');
        this.setState({ exportStatus });

        const data = window.location.hash.substr(1);
        if (exportStatus === 'true' && data) {
            importUserData(JSON.parse(decodeURIComponent(data)));
        }
    }
```

**Comment by sramezani** [comment]
Sorry, I replied veryyyyy late.
I used an approach similar to the things you suggested. (I forgot to reply here)
Now I don't use any database for storing data.
You can find my latest changes. :)

**Comment by bokub** [comment]
That's great to hear!

Thanks for your time :+1:
