### ISSUE TITLE
I can't open my exported PDF

### ISSUE THREAD

**Issue by coderkhalide** [sramezani/resume-builder#14]
I have build a resume for myself. but after exporting the PDF i can't open it.
this is what I see [https://prnt.sc/13c28me](https://prnt.sc/13c28me) [https://prnt.sc/13c2as9](https://prnt.sc/13c2as9)

**Comment by Landsil** [comment]
Same on ChromeOS on Windows 10.
Looks like pdf isn't generated, it's has 0 bytes size.

**Comment by sramezani** [comment]
The issue fixed.
